# basic options
title: Your awesome title
author: Masson Ma
email: masson.contact@gmail.com
description: A wonderful site
github_username: masson2013

# Build settings
markdown: kramdown
theme: minima
